export const possibleRoutes = [
  'introduction',
  'q1',
  'q2',
  'q3',
  'q4',
  'q5',
  'q6',
  'q7',
  'q8',
  'healthandmedical',
  'web3',
  'metavers',
  'genaiaccounting',
  'genaiengg',
  'genaisales',
  'genaiauto',
  'genaisec',
];

export const industries: string[] = [
  'Software / IT',
  'Agriculture',
  'Banking',
  'Business',
  'Clothing',
  'Construction',
  'Education',
  'Electrical Engineering',
  'Food',
  'Freelancing',
  'Graphic Designing',
  'Mechanical Engineering',
  'Medical',
  'News & Media',
  'Public Servant',
  'Sales',
  'Telecommunications',
  'Textile',
  'Tourism',
  'Transport',
  'Video Editing',
  'Other',
];

export const formQualifications: string[] = [
  'Matric / O Levels',
  'Intermediate / A Levels',
  "Undergraduate (Bachelor's)",
  "Graduate (Master's)",
  'Post-Graduate (PhD)',
];

export const years: string[] = [
  'Less then 1 year',
  '2 Years',
  '3 Years',
  '4 Years',
  '5 Years',
  '6 Years',
  '7 Years',
  '8 Years',
  '9 Years',
  '10+ Years',
];

export const employmentType: string[] = [
  'Full-time',
  'Part-time',
  'Self-employed',
  'Freelance',
  'Contract',
  'Internship',
  'Apprenticeship',
  'Seasonal',
];

export const formCities: string[] = [
  'Islamabad',
  'Ahmed Nager',
  'Ahmadpur East',
  'Ali Khan',
  'Alipur',
  'Arifwala',
  'Attock',
  'Bhera',
  'Bhalwal',
  'Bahawalnagar',
  'Bahawalpur',
  'Bhakkar',
  'Burewala',
  'Chillianwala',
  'Chakwal',
  'Chichawatni',
  'Chiniot',
  'Chishtian',
  'Daska',
  'Darya Khan',
  'Dera Ghazi',
  'Dhaular',
  'Dina',
  'Dinga',
  'Dipalpur',
  'Faisalabad',
  'Fateh Jhang',
  'Ghakhar Mandi',
  'Gojra',
  'Gujranwala',
  'Gujrat',
  'Gujar Khan',
  'Hafizabad',
  'Haroonabad',
  'Hasilpur',
  'Haveli',
  'Lakha',
  'Jalalpur',
  'Jattan',
  'Jampur',
  'Jaranwala',
  'Jhang',
  'Jhelum',
  'Kalabagh',
  'Karor Lal',
  'Kasur',
  'Kamalia',
  'Kamoke',
  'Khanewal',
  'Khanpur',
  'Kharian',
  'Khushab',
  'Kot Adu',
  'Jauharabad',
  'Lahore',
  'Lalamusa',
  'Layyah',
  'Liaquat Pur',
  'Lodhran',
  'Malakwal',
  'Mamoori',
  'Mailsi',
  'Mandi Bahauddin',
  'mian Channu',
  'Mianwali',
  'Multan',
  'Murree',
  'Muridke',
  'Mianwali Bangla',
  'Muzaffargarh',
  'Narowal',
  'Okara',
  'Renala Khurd',
  'Pakpattan',
  'Pattoki',
  'Pir Mahal',
  'Qaimpur',
  'Qila Didar',
  'Rabwah',
  'Raiwind',
  'Rajanpur',
  'Rahim Yar',
  'Rawalpindi',
  'Sadiqabad',
  'Safdarabad',
  'Sahiwal',
  'Sangla Hill',
  'Sarai Alamgir',
  'Sargodha',
  'Shakargarh',
  'Sheikhupura',
  'Sialkot',
  'Sohawa',
  'Soianwala',
  'Siranwali',
  'Talagang',
  'Taxila',
  'Toba Tek',
  'Vehari',
  'Wah Cantonment',
  'Wazirabad',
  'Badin',
  'Bhirkan',
  'Rajo Khanani',
  'Chak',
  'Dadu',
  'Digri',
  'Diplo',
  'Dokri',
  'Ghotki',
  'Haala',
  'Hyderabad',
  'Islamkot',
  'Jacobabad',
  'Jamshoro',
  'Jungshahi',
  'Kandhkot',
  'Kandiaro',
  'Karachi',
  'Kashmore',
  'Keti Bandar',
  'Khairpur',
  'Kotri',
  'Larkana',
  'Matiari',
  'Mehar',
  'Mirpur Khas',
  'Mithani',
  'Mithi',
  'Mehrabpur',
  'Moro',
  'Nagarparkar',
  'Naudero',
  'Naushahro Feroze',
  'Naushara',
  'Nawabshah',
  'Nazimabad',
  'Qambar',
  'Qasimabad',
  'Ranipur',
  'Ratodero',
  'Rohri',
  'Sakrand',
  'Sanghar',
  'Shahbandar',
  'Shahdadkot',
  'Shahdadpur',
  'Shahpur Chakar',
  'Shikarpaur',
  'Sukkur',
  'Tangwani',
  'Tando Adam',
  'Tando Allahyar',
  'Tando Muhammad',
  'Thatta',
  'Umerkot',
  'Warah',
  'Abbottabad',
  'Adezai',
  'Alpuri',
  'Akora Khattak',
  'Ayubia',
  'Banda Daud',
  'Bannu',
  'Batkhela',
  'Battagram',
  'Birote',
  'Chakdara',
  'Charsadda',
  'Chitral',
  'Daggar',
  'Dargai',
  'Darya Khan',
  'dera Ismail',
  'Doaba',
  'Dir',
  'Drosh',
  'Hangu',
  'Haripur',
  'Karak',
  'Kohat',
  'Kulachi',
  'Lakki Marwat',
  'Latamber',
  'Madyan',
  'Mansehra',
  'Mardan',
  'Mastuj',
  'Mingora',
  'Nowshera',
  'Paharpur',
  'Pabbi',
  'Peshawar',
  'Saidu Sharif',
  'Shorkot',
  'Shewa Adda',
  'Swabi',
  'Swat',
  'Tangi',
  'Tank',
  'Thall',
  'Timergara',
  'Tordher',
  'Awaran',
  'Barkhan',
  'Chagai',
  'Dera Bugti',
  'Gwadar',
  'Harnai',
  'Jafarabad',
  'Jhal Magsi',
  'Kacchi',
  'Kalat',
  'Kech',
  'Kharan',
  'Khuzdar',
  'Killa Abdullah',
  'Killa Saifullah',
  'Kohlu',
  'Lasbela',
  'Lehri',
  'Loralai',
  'Mastung',
  'Musakhel',
  'Nasirabad',
  'Nushki',
  'Panjgur',
  'Pishin valley',
  'Quetta',
  'Sherani',
  'Sibi',
  'Sohbatpur',
  'Washuk',
  'Zhob',
  'Ziarat',
];
