export const kp_cities = [
  'Abbottabad',
  'Adezai',
  'Alpuri',
  'Akora Khattak',
  'Ayubia',
  'Banda Daud Shah',
  'Bannu',
  'Batkhela',
  'Battagram',
  'Birote',
  'Buner',
  'Chakdara',
  'Charsadda',
  'Chitral',
  'Daggar',
  'Dargai',
  'Dera Ismail Khan',
  'Dir',
  'Drosh',
  'Hangu',
  'Haripur',
  'Karak',
  'Kohat',
  'Kundian',
  'Kulachi',
  'Lakki Marwat',
  'Landi Kotal',
  'Madyan',
  'Mansehra',
  'Mardan',
  'Mingora',
  'Nowshera',
  'Pabbi',
  'Peshawar',
  'Risalpur',
  'Saidu Sharif',
  'Shangla',
  'Shinkiari',
  'Swabi',
  'Swat',
  'Tangi',
  'Tank',
  'Thall',
  'Timergara',
  'Topi',
  'Tordher',
  'Barikot',
  'Matta',
  'Kabal',
  'Charbagh',
  'Darosh',

  'Kohistan',
  'Torkham',
  'Darra Adam Khel',
  'Jamrud',
  'Wana',
  'Parachinar',
  'Miranshah',
  'Bajaur',
  'Orakzai',
]
export const formQualifications = [
  'Matric / O Levels',
  'Intermediate / A Levels',
  "Undergraduate (Bachelor's)",
  "Graduate (Master's)",
  'Post-Graduate (PhD)',
]
export const formGenders = ['male', 'female']
